title: KimJooeon
author: KimJooeon
email: joo2theeon@gmail.com
description: Develog_by_KimJooeon
baseurl: "/jekyll-theme-kagami"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: K021
twitter_username:
instagram_username:

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
